/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @internal
 * Contains information about the style, such as the fill color or text alignment. For information about the JSON properties, see [Style](https://developers.miro.com/reference/style).
 */
export class Style {
  /**
   * Fill color. Default: `light_yellow`.
   */
  'fillColor'?: string | typeof Style.FillColorEnum[keyof typeof Style.FillColorEnum]
  /**
   * Defines how the  text is horizontally aligned. Default: `center`.
   */
  'textAlign'?: string | typeof Style.TextAlignEnum[keyof typeof Style.TextAlignEnum]
  /**
   * Defines how the  text is vertically aligned. Default: `top`.
   */
  'textAlignVertical'?:
    | string
    | typeof Style.TextAlignVerticalEnum[keyof typeof Style.TextAlignVerticalEnum]

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'fillColor',
      baseName: 'fillColor',
      type: 'Style.FillColorEnum',
    },
    {
      name: 'textAlign',
      baseName: 'textAlign',
      type: 'Style.TextAlignEnum',
    },
    {
      name: 'textAlignVertical',
      baseName: 'textAlignVertical',
      type: 'Style.TextAlignVerticalEnum',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return Style.attributeTypeMap
  }
}

export namespace Style {
  export const FillColorEnum = {
    Gray: 'gray',
    LightYellow: 'light_yellow',
    Yellow: 'yellow',
    Orange: 'orange',
    LightGreen: 'light_green',
    Green: 'green',
    DarkGreen: 'dark_green',
    Cyan: 'cyan',
    LightPink: 'light_pink',
    Pink: 'pink',
    Violet: 'violet',
    Red: 'red',
    LightBlue: 'light_blue',
    Blue: 'blue',
    DarkBlue: 'dark_blue',
    Black: 'black',
  } as const
  export const TextAlignEnum = {
    Left: 'left',
    Right: 'right',
    Center: 'center',
  } as const
  export const TextAlignVerticalEnum = {
    Top: 'top',
    Middle: 'middle',
    Bottom: 'bottom',
  } as const
}
